// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eblzvwqdzhbftdbwjgsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVibHp2d3FkemhiZnRkYndqZ3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzY0OTEsImV4cCI6MjA2MDM1MjQ5MX0.K7E9j91libBrjR3V2eGeW05fDHDiinFxk6jN2rd6EFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);